name: Merge Changes

on:
  pull_request:
    types:
      - closed

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Merge changes
        run: |
          git remote add source_repo https://github.com/DevangJoshiSains/main-release-test/tree/release
          git fetch source_repo
          git checkout main
          git merge source_repo/release --no-edit
          git push origin main
