name: Auto Merge

on:
  push:
    branches:
      - release  # Trigger the workflow on push event for release branch

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # This step checks out the repository where your workflow is running

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Merge to Main
        run: |
          git fetch origin main
          git checkout main
          git merge --no-edit release
          git push origin main
